 

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LockRouteImport } from './routes/lock'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupProfileRouteImport } from './routes/setup.profile'
import { Route as SetupCompleteRouteImport } from './routes/setup.complete'
import { Route as SetupAiRouteImport } from './routes/setup.ai'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCompleteRoute = SetupCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SetupRoute,
} as any)
const SetupAiRoute = SetupAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRoute
  '/developer': typeof DeveloperRoute
  '/devices': typeof DevicesRoute
  '/downloads': typeof DownloadsRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/lock': typeof LockRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
  '/voice': typeof VoiceRoute
  '/setup/ai': typeof SetupAiRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/profile': typeof SetupProfileRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRoute
  '/developer': typeof DeveloperRoute
  '/devices': typeof DevicesRoute
  '/downloads': typeof DownloadsRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/lock': typeof LockRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
  '/voice': typeof VoiceRoute
  '/setup/ai': typeof SetupAiRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/profile': typeof SetupProfileRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRoute
  '/developer': typeof DeveloperRoute
  '/devices': typeof DevicesRoute
  '/downloads': typeof DownloadsRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/lock': typeof LockRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
  '/voice': typeof VoiceRoute
  '/setup/ai': typeof SetupAiRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/profile': typeof SetupProfileRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/chat'
    | '/developer'
    | '/devices'
    | '/downloads'
    | '/files'
    | '/history'
    | '/lock'
    | '/memory'
    | '/models'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/system'
    | '/terminal'
    | '/voice'
    | '/setup/ai'
    | '/setup/complete'
    | '/setup/profile'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/chat'
    | '/developer'
    | '/devices'
    | '/downloads'
    | '/files'
    | '/history'
    | '/lock'
    | '/memory'
    | '/models'
    | '/projects'
    | '/settings'
    | '/system'
    | '/terminal'
    | '/voice'
    | '/setup/ai'
    | '/setup/complete'
    | '/setup/profile'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/chat'
    | '/developer'
    | '/devices'
    | '/downloads'
    | '/files'
    | '/history'
    | '/lock'
    | '/memory'
    | '/models'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/system'
    | '/terminal'
    | '/voice'
    | '/setup/ai'
    | '/setup/complete'
    | '/setup/profile'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  ChatRoute: typeof ChatRoute
  DeveloperRoute: typeof DeveloperRoute
  DevicesRoute: typeof DevicesRoute
  DownloadsRoute: typeof DownloadsRoute
  FilesRoute: typeof FilesRoute
  HistoryRoute: typeof HistoryRoute
  LockRoute: typeof LockRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
  SystemRoute: typeof SystemRoute
  TerminalRoute: typeof TerminalRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/profile': {
      id: '/setup/profile'
      path: '/profile'
      fullPath: '/setup/profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/complete': {
      id: '/setup/complete'
      path: '/complete'
      fullPath: '/setup/complete'
      preLoaderRoute: typeof SetupCompleteRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/ai': {
      id: '/setup/ai'
      path: '/ai'
      fullPath: '/setup/ai'
      preLoaderRoute: typeof SetupAiRouteImport
      parentRoute: typeof SetupRoute
    }
  }
}

interface SetupRouteChildren {
  SetupAiRoute: typeof SetupAiRoute
  SetupCompleteRoute: typeof SetupCompleteRoute
  SetupProfileRoute: typeof SetupProfileRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupAiRoute: SetupAiRoute,
  SetupCompleteRoute: SetupCompleteRoute,
  SetupProfileRoute: SetupProfileRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  ChatRoute: ChatRoute,
  DeveloperRoute: DeveloperRoute,
  DevicesRoute: DevicesRoute,
  DownloadsRoute: DownloadsRoute,
  FilesRoute: FilesRoute,
  HistoryRoute: HistoryRoute,
  LockRoute: LockRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
  SystemRoute: SystemRoute,
  TerminalRoute: TerminalRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
