import type { IVoiceService, AudioDevice } from "../interfaces/IVoiceService";

export class MockVoiceService implements IVoiceService {
  private recording = false;

  async startRecording(): Promise<void> {
    this.recording = true;
  }

  async stopRecording(): Promise<string> {
    this.recording = false;
    await new Promise((r) => setTimeout(r, 1000));
    return "This is a mocked transcript generated by MockVoiceService.";
  }

  isRecording(): boolean {
    return this.recording;
  }

  async listDevices(): Promise<AudioDevice[]> {
    return [
      { id: "mock-mic-1", name: "Default System Microphone", isDefault: true },
      { id: "mock-mic-2", name: "USB Condenser Mic", isDefault: false },
    ];
  }

  async setDevice(deviceId: string): Promise<void> {
    // mock no-op
  }

  async speak(text: string): Promise<void> {
    console.log(`[Mock TTS] Speaking: "${text}"`);
    await new Promise((r) => setTimeout(r, 2000));
  }

  async stopSpeaking(): Promise<void> {
    console.log(`[Mock TTS] Stopped speaking.`);
  }
}
